# Generated by Django 5.2.4 on 2025-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='personnel_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='personnel_permissions', to='auth.permission'),
        ),
    ]
