# Generated by Django 5.2.4 on 2025-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_personnel_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
