# Generated by Django 5.2.4 on 2025-08-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_personnel_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='badge_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
