# Generated by Django 5.2.4 on 2025-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_personnel_badge_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                ('officer_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('officer_type', models.CharField(blank=True, max_length=100)),
                ('regular_officer', models.CharField(blank=True, max_length=100)),
                ('civil_status', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('lifelong_learner', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('residential_address', models.TextField(blank=True)),
                ('residential_region', models.CharField(blank=True, max_length=100)),
                ('residential_province', models.CharField(blank=True, max_length=100)),
                ('residential_municipality', models.CharField(blank=True, max_length=100)),
                ('residential_barangay', models.CharField(blank=True, max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('permanent_region', models.CharField(blank=True, max_length=100)),
                ('permanent_province', models.CharField(blank=True, max_length=100)),
                ('permanent_municipality', models.CharField(blank=True, max_length=100)),
                ('permanent_barangay', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('father_first_name', models.CharField(blank=True, max_length=150)),
                ('father_middle_name', models.CharField(blank=True, max_length=150)),
                ('father_last_name', models.CharField(blank=True, max_length=150)),
                ('father_occupation', models.CharField(blank=True, choices=[('Housewife', 'Housewife'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('OFW', 'OFW')], max_length=50)),
                ('father_dob', models.DateField(blank=True, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=50)),
                ('father_region', models.CharField(blank=True, max_length=100)),
                ('father_province', models.CharField(blank=True, max_length=100)),
                ('father_municipality', models.CharField(blank=True, max_length=100)),
                ('father_barangay', models.CharField(blank=True, max_length=100)),
                ('mother_first_name', models.CharField(blank=True, max_length=150)),
                ('mother_middle_name', models.CharField(blank=True, max_length=150)),
                ('mother_last_name', models.CharField(blank=True, max_length=150)),
                ('mother_occupation', models.CharField(blank=True, choices=[('Housewife', 'Housewife'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('OFW', 'OFW')], max_length=50)),
                ('mother_dob', models.DateField(blank=True, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=50)),
                ('mother_region', models.CharField(blank=True, max_length=100)),
                ('mother_province', models.CharField(blank=True, max_length=100)),
                ('mother_municipality', models.CharField(blank=True, max_length=100)),
                ('mother_barangay', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
