# Generated by Django 5.2.4 on 2025-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_personnelprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
