# Generated by Django 5.2.4 on 2025-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
