# Generated by Django 5.2 on 2025-08-19 07:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_personnelprofile_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(blank=True, choices=[('Theft', 'Theft'), ('Robbery', 'Robbery'), ('Assault', 'Assault'), ('Homicide', 'Homicide'), ('Illegal Fishing', 'Illegal Fishing'), ('Smuggling', 'Smuggling'), ('Drugs', 'Drugs'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Others', 'Others')], default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('happened_at', models.DateField(blank=True, null=True)),
                ('v_first_name', models.CharField(blank=True, default='', max_length=120)),
                ('v_middle_name', models.CharField(blank=True, default='', max_length=120)),
                ('v_last_name', models.CharField(blank=True, default='', max_length=120)),
                ('v_age', models.CharField(blank=True, default='', max_length=10)),
                ('v_address', models.CharField(blank=True, default='', max_length=255)),
                ('v_region', models.CharField(blank=True, default='', max_length=120)),
                ('v_province', models.CharField(blank=True, default='', max_length=120)),
                ('v_city_municipality', models.CharField(blank=True, default='', max_length=120)),
                ('v_city_mun_kind', models.CharField(blank=True, default='', max_length=30)),
                ('v_barangay', models.CharField(blank=True, default='', max_length=120)),
                ('v_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('v_province_code', models.CharField(blank=True, default='', max_length=20)),
                ('v_city_mun_code', models.CharField(blank=True, default='', max_length=20)),
                ('v_barangay_code', models.CharField(blank=True, default='', max_length=20)),
                ('v_photo', models.ImageField(blank=True, null=True, upload_to=api.models.victim_upload_to)),
                ('s_first_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_middle_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_last_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_age', models.CharField(blank=True, default='', max_length=10)),
                ('s_crime_type', models.CharField(blank=True, default='', max_length=100)),
                ('s_address', models.CharField(blank=True, default='', max_length=255)),
                ('s_region', models.CharField(blank=True, default='', max_length=120)),
                ('s_province', models.CharField(blank=True, default='', max_length=120)),
                ('s_city_municipality', models.CharField(blank=True, default='', max_length=120)),
                ('s_city_mun_kind', models.CharField(blank=True, default='', max_length=30)),
                ('s_barangay', models.CharField(blank=True, default='', max_length=120)),
                ('s_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_province_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_city_mun_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_barangay_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_photo', models.ImageField(blank=True, null=True, upload_to=api.models.suspect_upload_to)),
                ('loc_address', models.CharField(blank=True, default='', max_length=255)),
                ('loc_region', models.CharField(blank=True, default='', max_length=120)),
                ('loc_province', models.CharField(blank=True, default='', max_length=120)),
                ('loc_city_municipality', models.CharField(blank=True, default='', max_length=120)),
                ('loc_city_mun_kind', models.CharField(blank=True, default='', max_length=30)),
                ('loc_barangay', models.CharField(blank=True, default='', max_length=120)),
                ('loc_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('loc_province_code', models.CharField(blank=True, default='', max_length=20)),
                ('loc_city_mun_code', models.CharField(blank=True, default='', max_length=20)),
                ('loc_barangay_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
                ('loc_kind', models.CharField(blank=True, default='', max_length=20)),
                ('loc_waterbody', models.CharField(blank=True, default='', max_length=120)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
