# Generated by Django 5.2 on 2025-08-19 08:12

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_crimereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='s_address',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_age',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_barangay',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_barangay_code',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_city_mun_code',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_city_mun_kind',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_city_municipality',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_crime_type',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_first_name',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_last_name',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_middle_name',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_photo',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_province',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_province_code',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_region',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='s_region_code',
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_first_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_middle_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_last_name', models.CharField(blank=True, default='', max_length=120)),
                ('s_age', models.CharField(blank=True, default='', max_length=10)),
                ('s_crime_type', models.CharField(blank=True, default='', max_length=100)),
                ('s_address', models.CharField(blank=True, default='', max_length=255)),
                ('s_region', models.CharField(blank=True, default='', max_length=120)),
                ('s_province', models.CharField(blank=True, default='', max_length=120)),
                ('s_city_municipality', models.CharField(blank=True, default='', max_length=120)),
                ('s_city_mun_kind', models.CharField(blank=True, default='', max_length=30)),
                ('s_barangay', models.CharField(blank=True, default='', max_length=120)),
                ('s_region_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_province_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_city_mun_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_barangay_code', models.CharField(blank=True, default='', max_length=20)),
                ('s_photo', models.ImageField(blank=True, null=True, upload_to=api.models.suspect_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='api.crimereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
