# Generated by Django 5.2.4 on 2025-08-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_suspect_latitude_suspect_loc_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Solved', 'Solved'), ('Unsolved', 'Unsolved')], default='Ongoing', max_length=20),
        ),
    ]
