# Generated by Django 5.2.4 on 2025-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_crimereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
