# Generated by Django 5.2.4 on 2025-09-22 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('badge_no', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('rank', models.CharField(blank=True, default='', max_length=64)),
                ('station', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.TextField(blank=True, default='')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='ids/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('request_info', 'Request Info'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('request_note', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_officers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['email'], name='api_officer_email_8a1dab_idx'), models.Index(fields=['badge_no'], name='api_officer_badge_n_1fbcaa_idx'), models.Index(fields=['verification_status'], name='api_officer_verific_6d7b86_idx')],
            },
        ),
    ]
