# Generated by Django 5.2.4 on 2025-09-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_officerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
