# Generated by Django 5.2.4 on 2025-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_personnelprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='rp_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_age',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_citizenship',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_middle_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_occupation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='rp_sex',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='v_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='v_citizenship',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='v_occupation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='v_place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='v_sex',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
