# Generated by Django 5.2.4 on 2025-10-13 10:47

from django.db import migrations, models
from django.utils import timezone
import random


def generate_blotter_number(prefix="R4A"):
    """
    Example: R4A-20251013-101530-12345
    """
    now = timezone.now()
    stamp = now.strftime("%Y%m%d-%H%M%S")
    rand = f"{random.randint(0, 99999):05d}"
    return f"{prefix}-{stamp}-{rand}"


def backfill_blotter_numbers(apps, schema_editor):
    CrimeReport = apps.get_model("api", "CrimeReport")

    # Track used values during the migration run (avoid duplicates in-batch)
    existing = set(
        CrimeReport.objects
        .exclude(blotter_number__isnull=True)
        .exclude(blotter_number="")
        .values_list("blotter_number", flat=True)
    )

    # Only fetch fields we need for speed/safety
    for obj in CrimeReport.objects.all().only("id", "blotter_number"):
        base = (obj.blotter_number or "").strip()

        # If empty, make a new candidate
        candidate = base or generate_blotter_number("R4A")

        # Ensure uniqueness vs DB + in-memory set
        suffix = 1
        while (
            CrimeReport.objects.filter(blotter_number=candidate).exclude(pk=obj.pk).exists()
            or candidate in existing
        ):
            # If base is empty, regenerate a fresh base each attempt (changes timestamp/rand)
            base_now = base or generate_blotter_number("R4A")
            candidate = f"{base_now}-{suffix:02d}"
            suffix += 1

        obj.blotter_number = candidate
        obj.save(update_fields=["blotter_number"])
        existing.add(candidate)


def noop_reverse(apps, schema_editor):
    # No reverse action needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_crimereport_rp_address_crimereport_rp_age_and_more"),
    ]

    operations = [
        # STEP 1: Add field as NULLABLE and NOT UNIQUE (SQLite-safe during table copy)
        migrations.AddField(
            model_name="crimereport",
            name="blotter_number",
            field=models.CharField(
                max_length=64,
                null=True,                 # allow nulls initially
                blank=True,
                default=None,
                help_text="Unique blotter number (server-generated if blank).",
            ),
        ),

        # STEP 2: Backfill unique values for all existing rows
        migrations.RunPython(backfill_blotter_numbers, reverse_code=noop_reverse),

        # STEP 3: Enforce uniqueness and not-null at the DB level
        migrations.AlterField(
            model_name="crimereport",
            name="blotter_number",
            field=models.CharField(
                max_length=64,
                unique=True,
                null=False,               # now required (your model.save() should auto-generate if blank)
                blank=True,
                help_text="Unique blotter number (server-generated if blank).",
            ),
        ),

        # STEP 4: Add your indexes
        migrations.AddIndex(
            model_name="crimereport",
            index=models.Index(fields=["blotter_number"], name="api_crimere_blotter_680315_idx"),
        ),
        migrations.AddIndex(
            model_name="crimereport",
            index=models.Index(fields=["is_archived", "created_at"], name="api_crimere_is_arch_1edba7_idx"),
        ),
    ]
