# Generated by Django 5.2.4 on 2025-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_personnel_totp_enabled_personnel_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
