# Generated by Django 5.2.4 on 2025-12-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_adminprofile_totp_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='totp_secret',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='totp_secret',
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='login', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
