# Generated by Django 5.2.4 on 2026-01-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_adminprofile_totp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='rp_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
