# Generated by Django 5.2 on 2026-03-29 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_crimereport_rp_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='desk_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
