# Generated by Django 5.2 on 2026-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_crimereport_desk_officer_crimereport_prepared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='crime_type',
            field=models.CharField(blank=True, choices=[('Piracy', 'Piracy (RPC Art. 122 / PD 532)'), ('Qualified Piracy', 'Qualified Piracy (RPC Art. 123 / RA 7659)'), ('Smuggling', 'Smuggling (RA 10863)'), ('Illegal Fishing', 'Illegal Fishing (RA 8550 / RA 10654)'), ('Dynamite Fishing', 'Dynamite Fishing (RA 8550)'), ('Cyanide Fishing', 'Cyanide Fishing (RA 8550)'), ('Foreign Poaching', 'Foreign Poaching (RA 8550)'), ('Marine Pollution', 'Marine Pollution / Oil Spill (PD 979 / RA 9275)'), ('Illegal Dumping', 'Illegal Waste Dumping (RA 9003)'), ('Wildlife Trafficking', 'Marine Wildlife Trafficking (RA 9147)'), ('Drug Trafficking', 'Drug Trafficking via Sea (RA 9165)'), ('Human Trafficking', 'Human Trafficking (RA 9208 / RA 10364)'), ('Illegal Firearms', 'Illegal Possession of Firearms (RA 10591)'), ('Unauthorized Entry', 'Unauthorized Foreign Vessel Entry (RA 12064)'), ('Overloading', 'Overloading Vessel (RA 9993)'), ('No Safety Equipment', 'No Safety Equipment (RA 9993)'), ('Unregistered Vessel', 'Unregistered Vessel (MARINA Laws)'), ('Ship Hijacking', 'Ship Hijacking / Vessel Seizure'), ('Vessel Theft', 'Vessel Theft'), ('Kidnapping', 'Kidnapping at Sea (RPC)'), ('Murder', 'Murder / Homicide at Sea (RPC)'), ('Missing Fisherman', 'Missing Fisherman / SAR Incident'), ('Maritime Accident', 'Maritime Accident / Collision'), ('Others', 'Others (Specify)')], default='', max_length=100),
        ),
    ]
